// Copyright (C) 1991-2010 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II Version 10.1 (Build Build 153 11/29/2010)
// Created on Wed Dec 07 13:49:52 2011

BigPart BigPart_inst
(
	.CountQ0(CountQ0_sig) ,	// input  CountQ0_sig
	.CountQ1(CountQ1_sig) ,	// input  CountQ1_sig
	.CountQ2(CountQ2_sig) ,	// input  CountQ2_sig
	.A(A_sig) ,	// output  A_sig
	.B(B_sig) 	// output  B_sig
);

