// Copyright (C) 1991-2010 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II Version 10.1 (Build Build 153 11/29/2010)
// Created on Wed Dec 07 13:50:04 2011

YourPart YourPart_inst
(
	.D0(D0_sig) ,	// input  D0_sig
	.D1(D1_sig) ,	// input  D1_sig
	.D2(D2_sig) ,	// input  D2_sig
	.OutputB(OutputB_sig) ,	// output  OutputB_sig
	.OutputA(OutputA_sig) 	// output  OutputA_sig
);

