DROP TABLE VRG_CUSTOMER_ARTIST_INT CASCADE CONSTRAINTS;

DROP TABLE VRG_TRANS CASCADE CONSTRAINTS;

DROP TABLE VRG_WORK CASCADE CONSTRAINTS;

DROP TABLE VRG_ARTIST CASCADE CONSTRAINTS;

DROP TABLE VRG_CUSTOMER CASCADE CONSTRAINTS;

DROP SEQUENCE VRGTransactionID;

DROP SEQUENCE VRGWorkID;

DROP SEQUENCE VRGArtistID;

DROP SEQUENCE VRGCustomerID;