CREATE SEQUENCE VRGCustomerID INCREMENT BY 1 START WITH 1000;
CREATE SEQUENCE VRGArtistID INCREMENT BY 1 START WITH 10;
CREATE SEQUENCE VRGWorkID INCREMENT BY 1 START WITH 500;
CREATE SEQUENCE VRGTransactionID INCREMENT BY 1 START WITH 100;