// Copyright (C) 1991-2010 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II Version 10.1 (Build Build 153 11/29/2010)
// Created on Fri Nov 18 19:05:17 2011

Lab4_and_5 Lab4_and_5_inst
(
	.InputA(InputA_sig) ,	// input  InputA_sig
	.InputB(InputB_sig) ,	// input  InputB_sig
	.InputC(InputC_sig) ,	// input  InputC_sig
	.InputD(InputD_sig) ,	// input  InputD_sig
	.OutputA(OutputA_sig) ,	// output  OutputA_sig
	.OutputB(OutputB_sig) ,	// output  OutputB_sig
	.OutputC(OutputC_sig) ,	// output  OutputC_sig
	.OutputD(OutputD_sig) ,	// output  OutputD_sig
	.OutputE(OutputE_sig) ,	// output  OutputE_sig
	.OutputF(OutputF_sig) ,	// output  OutputF_sig
	.OutputG(OutputG_sig) 	// output  OutputG_sig
);

